
  apiVersion: apps/v1
kind: Deployment
metadata:
  name: menulistitem-deployment
  labels:
    app: MenuListItem2001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuListItem2001
  template:
    metadata:
      labels:
        app: MenuListItem2001
    spec:
      containers:
      - name: menucontainer2001
        image: menucontainer2001.azurecr.io/menucontainer2001:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webiapisecretkey
---
apiVersion: v1
kind: Service
metadata:
  name: menulistitemsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuListItem2001
