
  apiVersion: apps/v1
kind: Deployment
metadata:
  name: MenuListItem2001
  labels:
    app: MenuListItem2001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuListItem2001
  template:
    metadata:
      labels:
        app: MenuListItem2001
    spec:
      containers:
      - name: MenuContainer2001
        image: dnazureacrcase.azurecr.io/dnazureacr:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: webiapisecretkey
---
apiVersion: v1
kind: Service
metadata:
  name: MenuListItem2001svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuListItem2001
